parameters:
#    ip_motors_settings.example.class: IPMotors\SettingsBundle\Example

services:
#    ip_motors_settings.example:
#        class: %ip_motors_settings.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
