<?php

namespace IPMotors\CustomerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends EntityRepository {

    public function search($key = null) {

       
        $query = $this->getEntityManager()
                        ->createQuery("
	            SELECT c FROM IPMotorsCustomerBundle:Customer c
	            WHERE c.nom LIKE :key "
                        );
        $query->setParameter('key', '%'.$key.'%');
        return $query->getResult();
    }
    
    public function exportData($parameters) 
    {
        
        $findBy = array();
        for($i = 0; $i<6; $i++) {
            if (isset($parameters['va' . $i]) && $parameters['va' . $i] != 0) {
                $findBy['choix' . $i] = $parameters['va' . $i];
            }
        }
        
        
        $vals = $this->findBy($findBy);
        
        $returnValue = array();
        
        foreach($vals as $customer) {
            $returnValue[] = $customer->getEmail();
        }
        
        return $returnValue;
        
    }

}
