<?php

namespace IPMotors\CustomerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends EntityRepository {

    public function search($key = null) {

       
        $query = $this->getEntityManager()
                        ->createQuery("
	            SELECT c FROM IPMotorsCustomerBundle:Customer c
	            WHERE c.nom LIKE :key "
                        );
        $query->setParameter('key', '%'.$key.'%');
        return $query->getResult();
    }

}
