<?php

namespace IPMotors\StrenghsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StrenghsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StrenghsRepository extends EntityRepository
{
}
