# Routing FOS
fos_user_security:
    resource: "routing/security.xml"

fos_user_profile:
   resource: "routing/profile.xml"
   prefix: /profile
 
fos_user_register:
   resource: "routing/registration.xml"
   prefix: /register
 
fos_user_resetting:
   resource: "routing/resetting.xml"
   prefix: /resetting
 
fos_user_change_password:
    resource: "routing/change_password.xml"
    prefix: /profile
    

        
ip_motors_users_list:
    pattern: /users
    defaults: { _controller: IPMotorsUserBundle:User:usersList }

ip_motors_promote_admin:
    pattern: /users/user/admin/{username}
    defaults: { _controller: IPMotorsUserBundle:User:promoteAdmin }

ip_motors_demote_admin:
    pattern: /users/user/simple/{username}
    defaults: { _controller: IPMotorsUserBundle:User:demoteAdmin }

ip_motors_activate_user:
    pattern: /users/user/activate/{username}
    defaults: { _controller: IPMotorsUserBundle:User:activateUser }

ip_motors_desactivate_user:
    pattern: /users/user/desactivate/{username}
    defaults: { _controller: IPMotorsUserBundle:User:desactivateUser }
    
    
ip_motors_add_user:
    pattern: /register/user/
    defaults: { _controller: IPMotorsUserBundle:User:addUser }

ip_motors_edit_user:
    pattern: /user/edit/{id}
    defaults: { _controller: IPMotorsUserBundle:User:editUser }