parameters:
#    ip_motors_user.example.class: IPMotors\UserBundle\Example

services:
    ipmotors_user.registration.form.type:
        class: IPMotors\UserBundle\Form\UserType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: ipmotors_userbundle_user_registration }
    ipmotors_user.profile.form.type:
        class: IPMotors\UserBundle\Form\UserProfile
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: ipmotors_userbundle_user_profile }