parameters:
#    ip_motors_strenghs.example.class: IPMotors\StrenghsBundle\Example

services:
#    ip_motors_strenghs.example:
#        class: %ip_motors_strenghs.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
