ip_motors_choices:
    resource: "@IPMotorsChoicesBundle/Resources/config/routing.yml"
    prefix:   /

ip_motors_form_edit:
    resource: "@IPMotorsFormEditBundle/Resources/config/routing.yml"
    prefix:   /

ip_motors_mail:
    resource: "@IPMotorsMailBundle/Resources/config/routing.yml"
    prefix:   /mailing

ip_motors_strenghs:
    resource: "@IPMotorsStrenghsBundle/Resources/config/routing.yml"
    prefix:   /

ip_motors_customer:
    resource: "@IPMotorsCustomerBundle/Resources/config/routing.yml"
    prefix:   /

ip_motors_web_service:
    resource: "@IPMotorsWebServiceBundle/Resources/config/routing.yml"
    prefix:   /

ip_motors_home:
    resource: "@IPMotorsHomeBundle/Resources/config/routing.yml"
    prefix:   /

ip_motors_user:
    resource: "@IPMotorsUserBundle/Resources/config/routing.yml"
    prefix:   /

ip_motors_marketing:
    resource: "@IPMotorsMarketingBundle/Resources/config/routing.yml"
    prefix:   /