parameters:
#    ip_motors_home.example.class: IPMotors\HomeBundle\Example

services:
#    ip_motors_home.example:
#        class: %ip_motors_home.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
