<?php

namespace IPMotors\MarketingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MarketingRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarketingRepository extends EntityRepository
{
}
