parameters:
#    ip_motors_choices.example.class: IPMotors\ChoicesBundle\Example

services:
#    ip_motors_choices.example:
#        class: %ip_motors_choices.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
