ip_motors_customer_homepage:
    pattern:  /customer
    defaults: { _controller: IPMotorsCustomerBundle:Default:index }

ip_motors_customer_read:
    path:      /customer/read/{id}
    defaults:  { _controller: IPMotorsCustomerBundle:Default:read }
    
ip_motors_customer_update:
    path:      /customer/update/{id}
    defaults:  { _controller: IPMotorsCustomerBundle:Default:update }
    
ip_motors_customer_delete:
    path:      /customer/delete/{id}
    defaults:  { _controller: IPMotorsCustomerBundle:Default:delete }
