ip_motors_customer_homepage:
    pattern:  /customer
    defaults: { _controller: IPMotorsCustomerBundle:Default:index }

ip_motors_customer_read:
    path:      /customer/{id}
    defaults:  { _controller: IPMotorsCustomerBundle:Default:read }
