parameters:
#    ip_motors_customer.example.class: IPMotors\CustomerBundle\Example

services:
#    ip_motors_customer.example:
#        class: %ip_motors_customer.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
