IPMotors\StrenghsBundle\Entity\Strenghs:
    type: entity
    table: null
    repositoryClass: IPMotors\StrenghsBundle\Entity\StrenghsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }
