<?php

namespace IPMotors\FormEditBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SurveyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SurveyRepository extends EntityRepository
{
    
    public function getCurrent()
    {
        $qb = $this->createQueryBuilder('s');
        $qb->where('s.activated = :value')
           ->setParameter('value', 1);

        return $qb->getQuery()
                  ->getSingleResult();
    }
}
