<?php

namespace IPMotors\FormEditBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SurveyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SurveyRepository extends EntityRepository
{
}
