ip_motors_mail_list:
    pattern:  /list
    defaults: { _controller: IPMotorsMailBundle:Mail:list }
    
ip_motors_mail_add:
    pattern:  /add
    defaults: { _controller: IPMotorsMailBundle:Mail:add }


ip_motors_mail_edit:
    pattern:  /edit/{id}
    defaults: { _controller: IPMotorsMailBundle:Mail:edit }
    requirements :
        id : \d+

ip_motors_mail_test:
    pattern:  /test
    defaults: { _controller: IPMotorsMailBundle:Mail:test }

ip_motors_mail_delete:
    pattern:  /delete/{id}
    defaults: { _controller: IPMotorsMailBundle:Mail:delete }
    requirements :
        id : \d+