parameters:
#    ip_motors_mail.example.class: IPMotors\MailBundle\Example

services:
#    ip_motors_mail.example:
#        class: %ip_motors_mail.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
